### ISSUE TITLE
Purchase order datagrid formatting on expand

### ISSUE THREAD

**Issue by adhurjaty** [adhurjaty/gobuddhabowls#2]
The purchase order datagrid gets wider when expanding to get category cost breakdown. Fix this so that it does not change the width of the table

**Comment by samling** [comment]
Need some more info to make sure I've got the right element, but can this possibly be fixed by changing the top-level div class in _datagrid.html from `container-fluid` to `container`? We could potentially use media queries to solve the formatting at different resolutions as well.
